import { Category, NewsItem } from "../types";

const placeholder = (seed: string) => `https://picsum.photos/seed/${seed}/1200/800`;

const newsByCategory: Record<Category, NewsItem[]> = {
  [Category.LATEST]: [
    {
      id: "latest-1",
      title: "تسارع مشاريع التصنيع الذكي في المقاطعات الصناعية الصينية",
      summary: "المجمعات الصناعية توسع خطوطها المؤتمتة مع تركيز واضح على الكفاءة، سلاسل الإمداد، وخفض زمن التسليم في القطاعات التقنية المتقدمة.",
      category: Category.LATEST,
      timestamp: "2026-05-01",
      imageUrl: placeholder("latest-1"),
    },
    {
      id: "latest-2",
      title: "ممرات لوجستية جديدة تدعم صادرات المعدات الهندسية",
      summary: "الربط بين الموانئ ومناطق التصنيع عزز سرعة الشحن وأعاد توزيع الحركة التجارية نحو مسارات أكثر كفاءة داخل الصين وخارجها.",
      category: Category.LATEST,
      timestamp: "2026-04-30",
      imageUrl: placeholder("latest-2"),
    },
    {
      id: "latest-3",
      title: "توسع الاستثمارات في مراكز البيانات والطاقة المساندة",
      summary: "المدن التقنية الكبرى ترفع قدرتها الاستيعابية عبر مشاريع جديدة للبنية الرقمية مع دمج حلول تبريد وطاقة أكثر استقرارًا.",
      category: Category.LATEST,
      timestamp: "2026-04-29",
      imageUrl: placeholder("latest-3"),
    },
    {
      id: "latest-4",
      title: "المصانع المتخصصة تعيد تصميم خطوط الإنتاج للطلب العالمي",
      summary: "التركيز الحالي يتجه نحو المرونة وسرعة التعديل على المنتجات بدل الاعتماد على دورات إنتاج طويلة وثابتة.",
      category: Category.LATEST,
      timestamp: "2026-04-28",
      imageUrl: placeholder("latest-4"),
    },
    {
      id: "latest-5",
      title: "نماذج الابتكار الإقليمي ترفع تنافسية المدن التقنية",
      summary: "تجارب الحاضنات والمناطق الاقتصادية الخاصة تمنح الشركات الناشئة مسارًا أسرع للتحول من البحث إلى الإنتاج الفعلي.",
      category: Category.LATEST,
      timestamp: "2026-04-27",
      imageUrl: placeholder("latest-5"),
    },
  ],
  [Category.ENGINEERING]: [
    {
      id: "eng-1",
      title: "جسور بحرية عملاقة تعيد تشكيل الربط بين المناطق الساحلية",
      summary: "المشاريع الهندسية الجديدة تقلص زمن التنقل وتفتح مسارات اقتصادية مباشرة بين موانئ ومراكز صناعية متباعدة.",
      category: Category.ENGINEERING,
      timestamp: "2026-04-25",
      imageUrl: placeholder("eng-1"),
    },
    {
      id: "eng-2",
      title: "أنفاق حضرية متعددة الاستخدام تدعم التوسع العمراني السريع",
      summary: "المدن الكبرى توظف حلول حفر متقدمة لدمج المترو والخدمات والبنية التحتية ضمن نطاقات حضرية كثيفة.",
      category: Category.ENGINEERING,
      timestamp: "2026-04-23",
      imageUrl: placeholder("eng-2"),
    },
    {
      id: "eng-3",
      title: "محطات نقل ذكية تُدار عبر أنظمة مراقبة لحظية",
      summary: "الاعتماد على التحليل التشغيلي المباشر سمح بخفض الاختناقات وتحسين استهلاك الطاقة في العقد اللوجستية.",
      category: Category.ENGINEERING,
      timestamp: "2026-04-20",
      imageUrl: placeholder("eng-3"),
    },
    {
      id: "eng-4",
      title: "مصانع مواد البناء المتقدمة تدعم المشاريع الضخمة",
      summary: "الإنتاج المحلي للمواد عالية الأداء يقلل كلفة التنفيذ ويمنح مرونة أكبر في مشروعات الجسور والأبراج.",
      category: Category.ENGINEERING,
      timestamp: "2026-04-18",
      imageUrl: placeholder("eng-4"),
    },
    {
      id: "eng-5",
      title: "تصميمات مقاومة للمناخ القاسي تدخل مشاريع البنية الجديدة",
      summary: "المنشآت الحديثة تدمج حلولًا لدرجات الحرارة القصوى والرياح والرطوبة ضمن دورة التصميم الأساسية.",
      category: Category.ENGINEERING,
      timestamp: "2026-04-15",
      imageUrl: placeholder("eng-5"),
    },
  ],
  [Category.AI]: [
    {
      id: "ai-1",
      title: "أتمتة المصانع تدخل مرحلة الاعتماد الواسع على الرؤية الحاسوبية",
      summary: "الأنظمة الجديدة تتعقب الجودة والأخطاء أثناء الإنتاج بدل الاكتفاء بالفحص النهائي، ما يرفع الدقة ويقلل الهدر.",
      category: Category.AI,
      timestamp: "2026-04-26",
      imageUrl: placeholder("ai-1"),
    },
    {
      id: "ai-2",
      title: "روبوتات الخدمة تنتقل من التجارب المحدودة إلى بيئات تشغيلية يومية",
      summary: "الاعتماد يتسع في المستودعات، الاستقبال، والدعم اللوجستي مع تحسين مستمر في الاستقلالية والاعتمادية.",
      category: Category.AI,
      timestamp: "2026-04-24",
      imageUrl: placeholder("ai-2"),
    },
    {
      id: "ai-3",
      title: "منصات التحليل الصناعي تتكامل مع بيانات التشغيل الحية",
      summary: "الجمع بين الحساسات والتحليلات التنبؤية يسمح بتقليل الأعطال وتخطيط الصيانة قبل توقف الخطوط.",
      category: Category.AI,
      timestamp: "2026-04-21",
      imageUrl: placeholder("ai-3"),
    },
    {
      id: "ai-4",
      title: "المدن الذكية توسع استخدام الأنظمة التنبؤية لإدارة المرور",
      summary: "النماذج التشغيلية الجديدة تربط الكاميرات، الإشارات، والخرائط الزمنية لتخفيف الازدحام في الساعات الحرجة.",
      category: Category.AI,
      timestamp: "2026-04-19",
      imageUrl: placeholder("ai-4"),
    },
    {
      id: "ai-5",
      title: "برمجيات الذكاء الصناعي الموجهة للقطاع الطبي تركز على الفرز الأولي",
      summary: "التطبيقات الحالية تستهدف دعم القرار وتسريع تنظيم الحالات دون استبدال التقييم الطبي المباشر.",
      category: Category.AI,
      timestamp: "2026-04-17",
      imageUrl: placeholder("ai-5"),
    },
  ],
  [Category.EV]: [
    {
      id: "ev-1",
      title: "شبكات الشحن السريع تتوسع حول العقد الصناعية والطرق السريعة",
      summary: "الاستثمار في محطات الشحن يركز على الموثوقية وتخفيض زمن الانتظار لتسريع تبني المركبات الكهربائية.",
      category: Category.EV,
      timestamp: "2026-04-26",
      imageUrl: placeholder("ev-1"),
    },
    {
      id: "ev-2",
      title: "مصانع البطاريات تعزز كفاءة التخزين الحراري والسلامة",
      summary: "التطوير الحالي يدور حول كثافة الطاقة، عمر الخلية، والتحكم الحراري في ظروف التشغيل المختلفة.",
      category: Category.EV,
      timestamp: "2026-04-22",
      imageUrl: placeholder("ev-2"),
    },
    {
      id: "ev-3",
      title: "منصات مركبات جديدة تستهدف التصدير والأسواق الناشئة",
      summary: "الشركات تعيد تصميم الفئات المتوسطة مع اهتمام أكبر بالتكلفة والصيانة وتوافر قطع الغيار.",
      category: Category.EV,
      timestamp: "2026-04-18",
      imageUrl: placeholder("ev-3"),
    },
    {
      id: "ev-4",
      title: "الموردون المحليون يرفعون إنتاج إلكترونيات القدرة",
      summary: "تعزيز المكونات الأساسية للمحركات والمحولات يدعم مرونة سلاسل التوريد ويقلل الاعتماد الخارجي.",
      category: Category.EV,
      timestamp: "2026-04-14",
      imageUrl: placeholder("ev-4"),
    },
    {
      id: "ev-5",
      title: "حلول إدارة الأساطيل الكهربائية تدخل قطاع النقل التجاري",
      summary: "التركيز يتحول من المركبة نفسها إلى البرمجيات التي تراقب الاستهلاك والشحن والجاهزية التشغيلية.",
      category: Category.EV,
      timestamp: "2026-04-12",
      imageUrl: placeholder("ev-5"),
    },
  ],
  [Category.SPACE]: [
    {
      id: "space-1",
      title: "برامج الاختبار الأرضي تدعم جيلًا جديدًا من المهام المدارية",
      summary: "سلاسل الاختبار الهندسي أصبحت أكثر تعقيدًا لرفع الاعتمادية قبل الإطلاق وتقليل مخاطر الأنظمة.",
      category: Category.SPACE,
      timestamp: "2026-04-27",
      imageUrl: placeholder("space-1"),
    },
    {
      id: "space-2",
      title: "التقنيات الروبوتية الفضائية تتوسع في خدمات الصيانة المدارية",
      summary: "الاهتمام يتزايد بالوحدات القادرة على الفحص والتثبيت والمناورة الدقيقة في البيئات القاسية.",
      category: Category.SPACE,
      timestamp: "2026-04-22",
      imageUrl: placeholder("space-2"),
    },
    {
      id: "space-3",
      title: "استثمارات الاستشعار عن بعد تدعم مراقبة الزراعة والبنية",
      summary: "البيانات الفضائية لم تعد محصورة في البحث العلمي، بل أصبحت جزءًا من القرار الاقتصادي والإداري.",
      category: Category.SPACE,
      timestamp: "2026-04-18",
      imageUrl: placeholder("space-3"),
    },
    {
      id: "space-4",
      title: "تكامل الحمولة والمركبة يختصر دورة التحضير للمهمات",
      summary: "النماذج الجديدة في التصميم التشغيلي تقلل الفجوة بين التطوير والاختبار والإطلاق.",
      category: Category.SPACE,
      timestamp: "2026-04-15",
      imageUrl: placeholder("space-4"),
    },
    {
      id: "space-5",
      title: "منشآت البحث الفضائي توسع شراكاتها مع الجامعات والمصانع",
      summary: "هذا الربط يعزز نقل المعرفة من المختبرات إلى التطبيقات الهندسية القابلة للتصنيع.",
      category: Category.SPACE,
      timestamp: "2026-04-11",
      imageUrl: placeholder("space-5"),
    },
  ],
  [Category.ENERGY]: [
    {
      id: "energy-1",
      title: "مزارع شمسية واسعة النطاق ترتبط بأنظمة تخزين متقدمة",
      summary: "التوسع في التخزين يهدف إلى استقرار الإمداد وتحسين الاستفادة من الإنتاج المتقلب عبر اليوم.",
      category: Category.ENERGY,
      timestamp: "2026-04-24",
      imageUrl: placeholder("energy-1"),
    },
    {
      id: "energy-2",
      title: "توربينات الرياح البحرية تدخل مرحلة تشغيل أكثر كفاءة",
      summary: "التطوير الحالي يركز على الصيانة البحرية، عمر المعدات، وربط المحطات بالشبكات الرئيسية.",
      category: Category.ENERGY,
      timestamp: "2026-04-21",
      imageUrl: placeholder("energy-2"),
    },
    {
      id: "energy-3",
      title: "برامج كفاءة الطاقة الصناعية تقلص استهلاك المصانع الثقيلة",
      summary: "الأنظمة الرقمية وأجهزة القياس الدقيقة أصبحت أداة أساسية لخفض الفاقد وتحسين التشغيل.",
      category: Category.ENERGY,
      timestamp: "2026-04-19",
      imageUrl: placeholder("energy-3"),
    },
    {
      id: "energy-4",
      title: "تحديث الشبكات الذكية يدعم الدمج الواسع للطاقة المتجددة",
      summary: "البنية الكهربائية الجديدة توفر مرونة أعلى في الموازنة والاستجابة للأحمال المتغيرة.",
      category: Category.ENERGY,
      timestamp: "2026-04-16",
      imageUrl: placeholder("energy-4"),
    },
    {
      id: "energy-5",
      title: "مراكز صناعية جديدة تتبنى حلول تبريد أقل استهلاكًا للطاقة",
      summary: "التحسينات التشغيلية لم تعد ثانوية، بل أصبحت جزءًا مباشرًا من جدوى الاستثمار في البنية التقنية.",
      category: Category.ENERGY,
      timestamp: "2026-04-13",
      imageUrl: placeholder("energy-5"),
    },
  ],
  [Category.TELECOM]: [
    {
      id: "telecom-1",
      title: "بنية الألياف والاتصالات الصناعية تدعم المصانع المتصلة",
      summary: "الشبكات الجديدة تستهدف زمن استجابة أقل وقدرة أكبر على ربط الأجهزة والحساسات في البيئات الإنتاجية.",
      category: Category.TELECOM,
      timestamp: "2026-04-23",
      imageUrl: placeholder("telecom-1"),
    },
    {
      id: "telecom-2",
      title: "تجارب الشبكات الخاصة تتوسع داخل المناطق اللوجستية",
      summary: "التركيز ينصب على الموثوقية التشغيلية وربط الرافعات والمركبات والأنظمة المركزية بشكل متزامن.",
      category: Category.TELECOM,
      timestamp: "2026-04-20",
      imageUrl: placeholder("telecom-2"),
    },
    {
      id: "telecom-3",
      title: "محطات ذكية تقلل استهلاك الطاقة في البنية اللاسلكية",
      summary: "التحسينات تشمل التبريد والإدارة البرمجية للأحمال بما يخفف الكلفة التشغيلية للمواقع.",
      category: Category.TELECOM,
      timestamp: "2026-04-17",
      imageUrl: placeholder("telecom-3"),
    },
    {
      id: "telecom-4",
      title: "تكامل الحوسبة الطرفية مع الشبكات يرفع كفاءة الخدمات الفورية",
      summary: "هذا النموذج يدعم تطبيقات النقل، المراقبة، والتشغيل الصناعي التي تتطلب معالجة قريبة من نقطة الاستخدام.",
      category: Category.TELECOM,
      timestamp: "2026-04-14",
      imageUrl: placeholder("telecom-4"),
    },
    {
      id: "telecom-5",
      title: "التركيز على أمن الشبكات يصبح جزءًا من التوسع التشغيلي",
      summary: "المشغلون يدمجون أدوات مراقبة واستجابة مبكرة مع ازدياد الاعتماد على البنية الرقمية الحرجة.",
      category: Category.TELECOM,
      timestamp: "2026-04-10",
      imageUrl: placeholder("telecom-5"),
    },
  ],
  [Category.BIOTECH]: [
    {
      id: "biotech-1",
      title: "منشآت التكنولوجيا الحيوية تطور خطوط إنتاج أكثر دقة",
      summary: "الاستثمار يركز على الموثوقية، الرقابة النوعية، ورفع القدرة على الانتقال من الاختبار إلى التصنيع.",
      category: Category.BIOTECH,
      timestamp: "2026-04-25",
      imageUrl: placeholder("biotech-1"),
    },
    {
      id: "biotech-2",
      title: "مختبرات التشخيص السريع تتوسع في حلول الفحص الميداني",
      summary: "المنتجات الجديدة تقلل زمن النتيجة وتدعم الخدمات الطبية في البيئات ذات الموارد المحدودة.",
      category: Category.BIOTECH,
      timestamp: "2026-04-22",
      imageUrl: placeholder("biotech-2"),
    },
    {
      id: "biotech-3",
      title: "برمجيات تحليل العينات ترفع كفاءة سلاسل العمل المخبرية",
      summary: "دمج الأتمتة والتحليل الرقمي يخفف الأخطاء البشرية ويسرّع تسليم النتائج التشغيلية.",
      category: Category.BIOTECH,
      timestamp: "2026-04-19",
      imageUrl: placeholder("biotech-3"),
    },
    {
      id: "biotech-4",
      title: "مناطق الابتكار الطبي تدعم شراكات بين الجامعات والمصنعين",
      summary: "هذا التقارب يختصر مسار التطوير ويزيد فرص تحويل الأفكار البحثية إلى منتجات قابلة للتسويق.",
      category: Category.BIOTECH,
      timestamp: "2026-04-15",
      imageUrl: placeholder("biotech-4"),
    },
    {
      id: "biotech-5",
      title: "تحديث البنية الحيوية الباردة يعزز نقل المنتجات الحساسة",
      summary: "تحسين سلسلة التبريد أصبح عاملًا حاسمًا في جودة التشغيل وتوسع التوزيع الإقليمي.",
      category: Category.BIOTECH,
      timestamp: "2026-04-12",
      imageUrl: placeholder("biotech-5"),
    },
  ],
  [Category.AGRITECH]: [
    {
      id: "agri-1",
      title: "المزارع الذكية تعتمد مراقبة دقيقة للمياه والتربة",
      summary: "الأنظمة المتصلة تمنح المزارعين قراءة أسرع لحالة الحقول وتساعدهم على تقليل الفاقد في الموارد.",
      category: Category.AGRITECH,
      timestamp: "2026-04-24",
      imageUrl: placeholder("agri-1"),
    },
    {
      id: "agri-2",
      title: "الطائرات المسيّرة تدخل إدارة المحاصيل على نطاق أوسع",
      summary: "الاستخدام العملي يتسع في الرش، المسح، ومتابعة النمو بدل بقائه ضمن نطاق التجارب المحدودة.",
      category: Category.AGRITECH,
      timestamp: "2026-04-21",
      imageUrl: placeholder("agri-2"),
    },
    {
      id: "agri-3",
      title: "سلاسل الإمداد الزراعية تتبنى تتبعًا رقميًا من المزرعة إلى السوق",
      summary: "التوثيق الرقمي يحسن الشفافية ويمنح المنتجين والتجار رؤية أوضح لحركة البضائع وجودتها.",
      category: Category.AGRITECH,
      timestamp: "2026-04-18",
      imageUrl: placeholder("agri-3"),
    },
    {
      id: "agri-4",
      title: "الزراعة داخل البيئات المغلقة تجذب استثمارات حضرية جديدة",
      summary: "المدن الكبيرة تنظر لهذه النماذج كحل للإنتاج القريب وتقليل أثر النقل على السلع الطازجة.",
      category: Category.AGRITECH,
      timestamp: "2026-04-15",
      imageUrl: placeholder("agri-4"),
    },
    {
      id: "agri-5",
      title: "معدات الحصاد الذكية ترفع الإنتاجية في المناطق واسعة المساحة",
      summary: "التحسينات الجديدة تركز على الدقة التشغيلية وتقليل الفاقد أثناء الجمع والنقل الأولي.",
      category: Category.AGRITECH,
      timestamp: "2026-04-11",
      imageUrl: placeholder("agri-5"),
    },
  ],
  [Category.QUANTUM]: [
    {
      id: "quantum-1",
      title: "مختبرات الحوسبة الكمية توسع بنيتها التجريبية",
      summary: "العمل الحالي يتركز على الاستقرار، التحكم، وتوسيع منصات الاختبار بدل الوعود التسويقية العامة.",
      category: Category.QUANTUM,
      timestamp: "2026-04-26",
      imageUrl: placeholder("quantum-1"),
    },
    {
      id: "quantum-2",
      title: "أبحاث المواد المتقدمة تدعم تطوير الرقائق الدقيقة",
      summary: "التقدم في المواد والبنية التصنيعية يبقى عنصرًا أساسيًا في تحسين الأداء والاعتمادية.",
      category: Category.QUANTUM,
      timestamp: "2026-04-22",
      imageUrl: placeholder("quantum-2"),
    },
    {
      id: "quantum-3",
      title: "الجامعات التقنية تربط أبحاث الفيزياء بالتطبيقات الصناعية",
      summary: "النموذج الجديد يدفع المشاريع من المختبر إلى التعاون مع الشركات المتخصصة في القياس والتحكم.",
      category: Category.QUANTUM,
      timestamp: "2026-04-18",
      imageUrl: placeholder("quantum-3"),
    },
    {
      id: "quantum-4",
      title: "اختبارات أنظمة التبريد الدقيقة تفتح مسارات بحث أوسع",
      summary: "الاستقرار الحراري والتحكم البيئي ما زالا من العوامل الحاسمة في أي تقدم عملي بهذا القطاع.",
      category: Category.QUANTUM,
      timestamp: "2026-04-14",
      imageUrl: placeholder("quantum-4"),
    },
    {
      id: "quantum-5",
      title: "منشآت القياس فائق الحساسية تخدم مشاريع الإلكترونيات المتقدمة",
      summary: "الاستثمار في أدوات القياس يعكس تركيزًا على البنية الأساسية العلمية وليس فقط على المخرجات النهائية.",
      category: Category.QUANTUM,
      timestamp: "2026-04-10",
      imageUrl: placeholder("quantum-5"),
    },
  ],
  [Category.ECONOMY]: [
    {
      id: "eco-1",
      title: "الاقتصاد الرقمي يوسع حضوره في الخدمات الصناعية والتجارية",
      summary: "النمو لا يقتصر على التطبيقات الاستهلاكية، بل يمتد إلى الشراء، النقل، والمراقبة التشغيلية.",
      category: Category.ECONOMY,
      timestamp: "2026-04-25",
      imageUrl: placeholder("eco-1"),
    },
    {
      id: "eco-2",
      title: "منصات التصدير التقنية تستفيد من بنية دفع ولوجستيات أكثر نضجًا",
      summary: "التكامل بين التجارة والخدمات الرقمية يمنح الشركات الأصغر قدرة أفضل على الوصول للأسواق الخارجية.",
      category: Category.ECONOMY,
      timestamp: "2026-04-21",
      imageUrl: placeholder("eco-2"),
    },
    {
      id: "eco-3",
      title: "الشركات الصناعية تعيد ترتيب إنفاقها نحو البرمجيات التشغيلية",
      summary: "الاستثمار يتحول من المعدات فقط إلى الأنظمة التي ترفع الرؤية والتحكم والقياس داخل المصنع.",
      category: Category.ECONOMY,
      timestamp: "2026-04-18",
      imageUrl: placeholder("eco-3"),
    },
    {
      id: "eco-4",
      title: "المناطق الاقتصادية الخاصة تختبر نماذج دعم أسرع للشركات الناشئة",
      summary: "التسهيلات الجديدة تركز على الوصول إلى التصنيع والشحن والتمويل الخدمي خلال مدد أقصر.",
      category: Category.ECONOMY,
      timestamp: "2026-04-14",
      imageUrl: placeholder("eco-4"),
    },
    {
      id: "eco-5",
      title: "تحسين كفاءة الموانئ ينعكس مباشرة على القطاعات التقنية المصدرة",
      summary: "كل خفض في زمن المناولة والتخليص يمنح المصنعين ميزة واضحة في الأسواق الحساسة للوقت.",
      category: Category.ECONOMY,
      timestamp: "2026-04-09",
      imageUrl: placeholder("eco-5"),
    },
  ],
};

export const getNewsByCategory = (category: Category, limit = 5): NewsItem[] =>
  newsByCategory[category].slice(0, limit);

export const getFeaturedNews = (): NewsItem | undefined =>
  newsByCategory[Category.LATEST][0];

export const getTickerItems = (): string[] =>
  newsByCategory[Category.LATEST].map((item) => item.title);

export const getEditorialSummary = (): string =>
  "المشهد التقني في الصين يتحرك حاليًا حول ثلاث نقاط واضحة: تصنيع أكثر ذكاءً، بنية تحتية أسرع، وربط أوثق بين الطاقة والبيانات والإنتاج.";
